language: php

php:
  - 8.0

dist: trusty
sudo: false

install: travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --colors=always --coverage-clover build/logs/clover.xml --testdox

after_success:
  - travis_retry php vendor/bin/php-coveralls
