language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

dist: trusty
sudo: false

install: travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
